trunk/dev531/src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

dev531/src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

dev531/src/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Salary__c</fullName>
        <label>Actual Salary</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Offers</relationshipLabel>
        <relationshipName>Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer_Date__c</fullName>
        <label>Offer Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Offer_Expiration_Date__c</fullName>
        <label>Offer Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFF-{0000}</displayFormat>
        <label>Offer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev531/src/classes/OfferGenerator.cls
public with sharing class OfferGenerator {

	public ID createCandidate(string firstName, string lastName){
		
		//Declare Candidate__c called newCandidate
		Candidate__c newCandidate = new Candidate__c();
		
		//Set the First_Name__c field to the parameter firstName
		newCandidate.First_Name__c = firstName;
		
		//Set the Last_Name__c field to the parameter lastName
		newCandidate.Last_Name__c = lastName;
		
		//Use the Database methods to Insert newCandidate 
		//Make sure to use a save results called results
		Database.SaveResult results = Database.insert(newCandidate);
		
		//Return the ID from the SaveResults object
		return results.getId();
	}


	public ID createJobApplication(ID candidateForJobAppId){
		
		//Declare Job_Application__c called jobApp
		Job_Application__c jobApp = new Job_Application__c();
		
		//Set the Candidate__c property of jobApp to to the ID 
		jobApp.Candidate__c  = candidateForJobAppId;
		
		//Use the Database methods to Insert jobApp
		//Make sure to use a save results
		Database.SaveResult results = Database.insert(jobApp);
		
		//Return the ID from the SaveResults object
		return results.getId();
	}
	
	
	public ID createOffer(ID jobAppForOfferId){
		
		Offer__c newOffer = new Offer__c();
		
		//Set the Offer_Date__c to today's date
		newOffer.Offer_Date__c = Date.today();
		
		//Set the Offer_Expiration_Date__c to one one month from today
		newOffer.Offer_Expiration_Date__c = Date.today().addMonths(1);
		
		//Set the Actual_Salary__c of newOffer to $60,000
		newOffer.Actual_Salary__c = 60000;
		
		//Set the Status__c of newOffer to Sent
		newOffer.Status__c ='Sent';
		
		//Set the Job_Application__c of newOffer to the ID of jobApp
		newOffer.Job_Application__c = jobAppForOfferId;
		
		//Use the Database methods to insert new offer
		//Make sure to use a save results
		Database.SaveResult results = Database.insert(newOffer);
		
		//Return the ID from the SaveResults object
		return results.getId();
	}
}