trunk/timeware/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

timeware/src/objects/Location__c.object
<CustomObject>
    <description>An entity within an organization where employee&apos;s are grouped for reporting purposes and security.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is location available for use? Using flag instead of deleting location.</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Enter a description for this location.</description>
        <label>Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

timeware/src/classes/zLookupToPicklistExtension.cls
public class zLookupToPicklistExtension {

    private final ApexPages.standardController controller;

    private final Employee__c obj;

    public zLookupToPicklistExtension(ApexPages.StandardController stdController) {
        this.controller = stdController;
        this.obj = (Employee__c)stdController.getRecord();
    }

    public SelectOption[] getLocationOptions() {
        SelectOption[] locations = new SelectOption[]{};
        /*locations.add(new SelectOption('','–None–'));*/
        for (Location__c l : [select name, description__c from location__c where active__c = true order by name]) {
            locations.add(new SelectOption(l.name, l.name + ' ' + l.description__c));
        }
        return locations;
    }
}