trunk/appointment/src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>All_Day__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Day</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Customer</label>
        <referenceTo>Customer__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Duration_In_Minutes__c</fullName>
        <label>Duration</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Staff_Service__c</fullName>
        <label>Staff Service</label>
        <referenceTo>Staff_Service__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_DateTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stop_DateTime__c</fullName>
        <label>Stop Time</label>
        <type>DateTime</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

appointment/src/objects/Appointment__c.object
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>

appointment/src/objects/Appointment__c.object
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

trunk/appointment/src/objects/Customer__c.object
<CustomObject>
    <description>Customer is the person we are scheduling.</description>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>IF(AND(ISBLANK(Last_Name__c ),ISBLANK(First_Name__c )), 
NULL, 
IF(ISBLANK(Last_Name__c ), TRIM(First_Name__c), TRIM(Last_Name__c) &amp; &quot;, &quot; &amp; TRIM(First_Name__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <description>Default Service.  If chosen used to determine length of time for recurring appointments.</description>
        <inlineHelpText>Enter Service to be performed if Recurring is checked.</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Customers</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Customer Status</description>
        <inlineHelpText>Enter Customer&apos;s Status.  Default is Active.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/appointment/src/objects/Service__c.object
<CustomObject>
    <description>Services you provide.</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

appointment/src/objects/Service__c.object
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

trunk/appointment/src/objects/Staff__c.object
<CustomObject>
    <description>Staff who provide your services.</description>
    <label>Staff</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

appointment/src/objects/Staff__c.object
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>IF(AND(ISBLANK(Last_Name__c ),ISBLANK(First_Name__c )), 
NULL, 
IF(ISBLANK(Last_Name__c ), TRIM(First_Name__c), TRIM(Last_Name__c) &amp; &quot;, &quot; &amp; TRIM(First_Name__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>

trunk/appointment/src/objects/Staff_Service__c.object
<CustomObject>
    <description>Junction for staff and service.</description>
    <fields>
        <fullName>Service__c</fullName>
        <description>Service Assigned</description>
        <inlineHelpText>Enter service.</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Staff Services</relationshipLabel>
        <relationshipName>Staff_Services</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <description>Staff assigned</description>
        <inlineHelpText>Enter Staff</inlineHelpText>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Staff Services</relationshipLabel>
        <relationshipName>Staff_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff Service</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Staff Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/appointment/src/classes/getJSONAppointments.cls
public class getJSONAppointments {

    public JSONObject json {get;set;}
    
    /* invoked on an Ajax request */    
    public void getAppointments() 
    {

        try
        {

            Map<string,string> params = ApexPages.currentPage().getParameters();
            json = new JSONObject();
            
            // Do SOQL query to see if there are any records !
            List<Appointment__c> records = new List<Appointment__c>();
            datetime startDate = datetime.newInstance(0);
            Integer startInt = integer.valueOf(params.get('start'));
            startDate = startDate.addSeconds(startInt);
            
            datetime endDate = datetime.newInstance(0);
            Integer endInt = integer.valueOf(params.get('end'));
            endDate = endDate.addSeconds(endInt);
            
            records = [Select Id,
                              Start_DateTime__c,
                              Stop_DateTime__c,
                              Duration_In_Minutes__c,
                              Customer__r.Full_Name__c,
                              Staff_Service__r.Staff__r.Full_Name__c,
                              Staff_Service__r.Service__r.Name,
                              Status__c
                              from Appointment__c 
                              where Start_DateTime__c>=:startDate 
                              and Stop_DateTime__c<=:endDate ];

            List<JSONObject.value> values = new List<JSONObject.value>(); 

            System.debug(Logginglevel.ERROR);           
            System.debug(Logginglevel.INFO, 'Start Param '+params.get('start')+' End Param' +params.get('end'));     
                  
            if (!records.isEmpty()) 
            {

                // JSONify the results !
                String ProjectName;
                for (Appointment__c a : records) 
                {

                    try
                    {
                    
                        JSONObject cjson = new JSONObject();
                        cjson.putOpt('"id"', new JSONObject.value(a.Id));
                        
                        // ProjectName = a.Project_Name__c.replace('"' , '');
                        
                        // cjson.putOpt('"title"', new JSONObject.value(a.Project_Number__c + ' ' +ProjectName+ ' N: '+a.Study_N__c+ ' ' +a.Location__r.name));
                        // cjson.putOpt('"allDay"', new JSONObject.value(a.All_Day__c));
        
                        // Convert the times into unix timestamp format for the calendar
                        Long startDateTime = a.Start_DateTime__c.getTime()/1000;
                        Long endDateTime = a.Stop_DateTime__c.getTime()/1000;
        
                        cjson.putOpt('"start"', new JSONObject.value(startDateTime.intValue()));
                        cjson.putOpt('"end"', new JSONObject.value(endDateTime.intValue()));
                        cjson.putOpt('"duration"', new JSONObject.value(a.Duration_In_Minutes__c));
                        cjson.putOpt('"customer"', new JSONObject.value(a.Customer__r.Full_Name__c));
                        cjson.putOpt('"staff"', new JSONObject.value(a.Staff_Service__r.Staff__r.Full_Name__c));
                        cjson.putOpt('"service"', new JSONObject.value(a.Staff_Service__r.Service__r.Name));
                        cjson.putOpt('"status"', new JSONObject.value(a.Status__c));
                        cjson.putOpt('"linkurl"', new JSONObject.value('https://na5.salesforce.com/'+a.Id));

                        // cjson.putOpt('"client"', new JSONObject.value(a.Client__c));
                        // cjson.putOpt('"PM"', new JSONObject.value(a.Project_Manager__c));
                        // cjson.putOpt('"PA"', new JSONObject.value(a.Project_Associate__c));
                        // cjson.putOpt('"status"', new JSONObject.value(a.status__c));
                        // cjson.putOpt('"test"', new JSONObject.value(a.Project_Name__c));
                        // cjson.putOpt('"linkurl"', new JSONObject.value('https://na2.salesforce.com/'+a.Id));
                        // cjson.putOpt('"className"', new JSONObject.value(a.status__c + ' ' + a.Id + ' ' + a.Local_Remote_Indicator__c));
                        // cjson.putOpt('"StudyN"', new JSONObject.value(a.Study_N__c));         
                        // cjson.putOpt('"Location"', new JSONObject.value(a.Location__r.name)); 
                        // cjson.putOpt('"LRIndicator"', new JSONObject.value(a.Local_Remote_Indicator__c)); 
                        values.add(new JSONObject.value(cjson));
                        
                    }
                    catch(Exception e)
                    {
                        System.debug(Logginglevel.ERROR);
                        System.debug(Logginglevel.INFO, 'ERROR: Start Param '+params.get('start')+' End Param: ' +params.get('end')+' Error: '+e.getMessage());
                    }
                }    
            }
            else
            {
                JSONObject cjson = new JSONObject();
                cjson.putOpt('"data"', new JSONObject.value('No query records found. Start Param '+params.get('start')+' End Param' +params.get('end')));                  
                values.add(new JSONObject.value(cjson));               
            }

            json.putOpt('appointments', new JSONObject.value(values));

        }
        catch(Exception e)
        {
             Map<string,string> params = ApexPages.currentPage().getParameters();
             json = new JSONObject();            
             List<JSONObject.value> values = new List<JSONObject.value>();
             JSONObject cjson = new JSONObject();
             cjson.putOpt('"data"', new JSONObject.value('ERROR. Start Param: '+params.get('start')+' End Param: ' +params.get('end')+ 'Error: '+e.getMessage()));                  
             values.add(new JSONObject.value(cjson));  
             json.putOpt('appointments', new JSONObject.value(values));        
        }        

    }

    // Returns the JSON result string
    public String getResult() 
    {

       string jsonString = json.ValuetoString();
       jsonString = jsonString.replace('{appointments: [' , '[');
       jsonString = jsonString.replace('}]}' , '}]');
       return jsonString;
       
    }
    
}