trunk/appointment/src/objects/Service__c.object
<CustomObject>
    <description>Services you provide.</description>
    <fields>
        <fullName>Service_Category__c</fullName>
        <inlineHelpText>Select the appropriate Service Category for your service.</inlineHelpText>
        <label>Service Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

appointment/src/objects/Service__c.object
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>

trunk/appointment/src/objects/Service_Category__c.object
<CustomObject>
    <description>Categories are used to group services together.</description>
    <fields>
        <fullName>Staff__c</fullName>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Categories</relationshipLabel>
        <relationshipName>Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/appointment/src/objects/Staff__c.object
<CustomObject>
    <description>Staff who provide your services.</description>
    <label>Staff</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

appointment/src/objects/Staff__c.object
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>IF(AND(ISBLANK(Last_Name__c ),ISBLANK(First_Name__c )), 
NULL, 
IF(ISBLANK(Last_Name__c ), TRIM(First_Name__c), TRIM(Last_Name__c) &amp; &quot;, &quot; &amp; TRIM(First_Name__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>

trunk/appointment/src/objects/Staff_Service__c.object
<CustomObject>
    <description>Junction for staff and service.</description>
    <fields>
        <fullName>Service__c</fullName>
        <description>Service Assigned</description>
        <inlineHelpText>Enter service.</inlineHelpText>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Staff Services</relationshipLabel>
        <relationshipName>Staff_Services</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff__c</fullName>
        <description>Staff assigned</description>
        <inlineHelpText>Enter Staff</inlineHelpText>
        <label>Staff</label>
        <referenceTo>Staff__c</referenceTo>
        <relationshipLabel>Staff Services</relationshipLabel>
        <relationshipName>Staff_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Staff Service</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>Staff Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/appointment/src/classes/StaffServiceSOQLQuery.cls
public class StaffServiceSOQLQuery {

    // Staff_Service__c[] ssj = [
    List<Staff_Service__c> ssj = [
        select Staff__r.Id, Staff__r.Name, Staff__r.Full_Name__c, Service__r.Id, Service__r.Name, Service__r.Service_Category__c
        from Staff_Service__c
        // where Policy__c = :policyId
        ];
        
    //List<Staff__c> staffing = new List<Staff__c>();
    //List<Service__c> services = new List<Service__c>();
    
    //for (Staff_Service__c ss : ssj) {
    
        //if (ss.Staff__r != null) {
        //    staffing.add(ss.Staff__r);
        //}
        //if (ss.Service__r != null) {
        //    services.add(ss.Service__r);
        //}
        
    //}
    
}