trunk/appointment/src/objects/zProjectItem__c.object
<CustomObject>
    <description>An Approach to In-Place Editing with Visualforce by Ryan Marples</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weighting__c</fullName>
        <label>Weighting</label>
        <picklist>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>zProjectItem</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>zProjectItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

trunk/appointment/src/classes/zProjectsController.cls
public class zProjectsController { 
    
    public zProjectItem__c newProject { get; set; }
    
    public zProjectItem__c editProject { get; set; }

    public zProjectsController() {
        newProject = new zProjectItem__c();
    }
    
    public zProjectItem__c[] getProjects() {
        return [SELECT Name, Status__c, Weighting__c FROM zProjectItem__c WHERE OwnerId = :UserInfo.getUserId() 
                ORDER BY CreatedDate DESC];
    }
    
    public String getParam(String name) {
        return ApexPages.currentPage().getParameters().get(name);   
    }
    
    public PageReference add() {
        try {
            INSERT newProject;
            // if successful, reset the new project for the next entry
            newProject = new zProjectItem__c();
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
        return null;
    }
     
    public PageReference del() {
        try {
            String delid = getParam('delid');
            zProjectItem__c project = [SELECT Id FROM zProjectItem__c WHERE ID=:delid];
            DELETE project;
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
        return null;
    }
    
    public PageReference edit() {
        String editid = getParam('editid');
        editProject = [SELECT Name, Status__c, Weighting__c FROM zProjectItem__c WHERE Id=:editid];
        return null;
    }
    
    public PageReference cancelEdit() {
        editProject = null;
        return null;
    }
    
    public PageReference saveEdit() {
        try {
            UPDATE editProject;
            editProject = null;
        } catch (Exception e) {
            ApexPages.addMessages(e);
        }
        return null;
    }
        
}