dev531/src/objects/Job_Posting__c.object
<CustomObject>
    <fields>
        <fullName>Job_Posting_Site__c</fullName>
        <label>Job Posting Site</label>
        <referenceTo>Job_Posting_Site__c</referenceTo>
        <relationshipLabel>Job Postings</relationshipLabel>
        <relationshipName>R00N30000005QQPCEA4</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Postings</relationshipLabel>
        <relationshipName>R00N30000005QQPDEA4</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job Posting</label>
    <nameField>
        <displayFormat>JOBPOST-{0000}</displayFormat>
        <label>Job Posting Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Postings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

trunk/dev531/src/objects/Job_Posting_Site__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Job Posting Site</label>
    <nameField>
        <displayFormat>JOBSITE-{0000}</displayFormat>
        <label>Job Posting Site Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Posting Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dev531/src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

dev531/src/classes/JobPostingManager.cls
public with sharing class JobPostingManager {
 	
 	//Public attribute for position
    public Position__c position;
    
    //Constructor that accepts a position
    public JobPostingManager(Position__c constructorPosition) {
    	 //Assign the passed constructor value to the public attribute
    	 constructorPosition = position;
    }
    
    public void createJobPosting() {	
    	//Declare a list for the active job sites
		List<Job_Posting_Site__c> activeJobSites = new List<Job_Posting_Site__c>();
		
		//Get the list of the 'Active' sites
		activeJobSites = 
			[SELECT ID FROM Job_Posting_Site__c WHERE Status__c='A'];
		
		//Loop through the job sites and add the posting
		for(Job_Posting_Site__c jobSite : activeJobSites){		
			
			//Declare a new job posting
			Job_Posting__c job_posting = new Job_Posting__c();
			
			//Set the position for the posting from the public attribute
			job_posting.Position__c = position.Id;
			
			//Set the job posting site from the jobSite
			job_posting.Job_Posting_Site__c = jobSite.Id;
			
			//insert the posting
			insert job_posting;	
		}
    }
}