appointment/src/objects/Staff__c.object
<CustomObject>
    <description>Staff who provide your services.</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Enter an &apos;Email Address&apos; for resource.</description>
        <inlineHelpText>Please enter an email address for resource.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Enter the &apos;First Name&apos; for resource.</description>
        <inlineHelpText>Please enter the first name for resource.</inlineHelpText>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Enter the &apos;Last Name&apos; for resource.</description>
        <inlineHelpText>Please enter the last name for resource.</inlineHelpText>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Staff</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

appointment/src/classes/ProcessStaffEmail.cls
global class ProcessStaffEmail implements Messaging.InboundEmailHandler {
 
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
 
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
 
        Staff__c staff = new Staff__c();
        staff.First_Name__c = email.fromname.substring(0,email.fromname.indexOf(' '));
        staff.Last_Name__c = email.fromname.substring(email.fromname.indexOf(' '));
        staff.Email__c = envelope.fromAddress;
        insert staff;
 
        System.debug('====> Created staff '+staff.Id);
 
        if (email.binaryAttachments != null && email.binaryAttachments.size() > 0) {

            for (integer i = 0 ; i < email.binaryAttachments.size() ; i++) {
                Attachment attachment = new Attachment();
                // attach to the newly created staff record
                attachment.ParentId = staff.Id;
                attachment.Name = email.binaryAttachments[i].filename;
                attachment.Body = email.binaryAttachments[i].body;
                insert attachment;
            }

        }
 
        return result;
 
    }

    static testMethod void testMe() {

        // create a new email and envelope object
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
 
        // setup the data for the email
        email.subject = 'Test Job Applicant';
        email.fromname = 'FirstName LastName';
        env.fromAddress = 'someaddress@email.com';
 
        // add an attachment
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf('my attachment text');
        attachment.fileName = 'textfile.txt';
        attachment.mimeTypeSubType = 'text/plain';
 
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
 
        // call the email service class and test it with the data in the testMethod
        ProcessStaffEmail emailProcess = new ProcessStaffEmail();
        emailProcess.handleInboundEmail(email, env);
 
        // query for the staff the email service created
        Staff__c staff = [select Id, First_Name__c, Last_Name__c, Email__c from Staff__c
          where First_Name__c = 'FirstName' and Last_Name__c = 'LastName'];
 
        System.assertEquals(staff.First_Name__c,'FirstName');
        System.assertEquals(staff.Last_Name__c,'LastName');
        System.assertEquals(staff.Email__c,'someaddress@email.com');
 
        // find the attachment
        Attachment a = [select name from attachment where parentId = :staff.id];
 
        System.assertEquals(a.name,'textfile.txt');
 
    }

}