appointment/src/objects/zCat3__c.object
<CustomObject>
    <description>Jeff Douglas Sample Code</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>zCategory</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>zCategories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

appointment/src/classes/zCategoryWrapper.cls
public class zCategoryWrapper {

    public Boolean checked{ get; set; }
    public zCat3__c cat { get; set;}

    public zCategoryWrapper(){
        cat = new zCat3__c();
        checked = false;
    }

    public zCategoryWrapper(zCat3__c c){
        cat = c;
        checked = false;
    }

    public static testMethod void testMe() {

        zCategoryWrapper cw = new zCategoryWrapper();
        System.assertEquals(cw.checked,false);      

        zCategoryWrapper cw2 = new zCategoryWrapper(new zCat3__c(name__c='Test1'));
        System.assertEquals(cw2.cat.name__c,'Test1');
        System.assertEquals(cw2.checked,false);     

    }

}